### PR TITLE
Guidance

### PR DESCRIPTION
**Pull request by amazingphilippe**
# Summary | Résumé

For use in testing lundi. 

@EliseKa 

Il devrait y avoir tout ce qu'il faut pour tester les guides en français et les petits changements sur la page de création de gabarit.

### CODE REVIEW

**Review by EliseKa — APPROVED** [review]
Looks good! The deployment wasn't working so I only looked at the files changed, and it seemed correct.

**Comment by amazingphilippe** [comment]
Hmm. That's a weird one. We don't want to merge this, and we need to use the deployment for the testing sessions. Any ideas on what's happening with the deployment here? @sastels

**Comment by amazingphilippe** [comment]
Or maybe is it only the homepage that decided to not work?

**Comment by EliseKa** [comment]
Oh you're right - I can access the sign-in page. However my credentials don't work because they're either associated to the cdssandbox url or the production url, not the deployment url...

**Comment by amazingphilippe** [comment]
I used credentials I normally use on the staging site

**Comment by EliseKa** [comment]
not sure what happened, but once again you're right! I must have used an old credential. I've been able to log in 👍

**Comment by EliseKa** [comment]
Alright, I found one thing to fix: in the formatting guide, the "Emphasis" title is in English and should be "Bloc de texte en retrait"
Capture d’écran, le 2021-12-13 à 15 33 41

**Comment by amazingphilippe** [comment]
@jimleroyer There are more files changed in this PR than necessary. Any idea why?

**Comment by amazingphilippe** [comment]
Link to cds-snc/notification-planning#193 and cds-snc/notification-planning#190

**Comment by jimleroyer** [comment]
@amazingphilippe We are not using `main` as our main branch and that PR targets `master`. Hence `master` is not trailing behind (and soon to be dumped) and this PR is bringing more files in there.

**Review by jimleroyer — APPROVED** [review]
:shipit:

**Pull request merged**
