### PR TITLE
Bmw translate 2

### PR DESCRIPTION
**Pull request by willeybryan**
- Translation batch 2 returned from Translation services
- Elises edits to batch 1

### CODE REVIEW

**Comment by timarney** [comment]
Doing a test conflict fix here - https://github.com/cds-snc/notification-admin/pull/146

**Comment by timarney** [comment]
@willeybryan preview link here if you want to review

https://notification-canada-ca-pr-146.herokuapp.com

**Comment by willeybryan** [comment]
Fancy! But with Two factor on I don't think I can actually sign in, but what I can see looks good

**Comment by willeybryan** [comment]
NVM, got by appending the URL after local host to the Heroku domain

**Comment by willeybryan** [comment]
LGTM

**Comment by timarney** [comment]
Will merge via #146

**Pull request closed without merging**
