### PR TITLE
Fix "preview page server error" bug

### PR DESCRIPTION
**Pull request by smcmurtry**
# Summary | Résumé

I ran this with the debugger and discovered that the `template` object is an empty dict if we have not yet visited the preview page by clicking on the link. This is because the key/value that stores this info (see the `get_preview_data` fn) has not yet been set in Redis. If this is the case, we can use the `get_template_with_user_permission_or_403` method, which makes a request to the API.

# Test instructions | Instructions pour tester la modification

See the attached issue.

### CODE REVIEW

**Review by sastels — APPROVED** [review]
Tested locally, can go directly to template page, and "Save" and "Edit" buttons work appropriately.

**Comment by smcmurtry** [comment]
@jimleroyer we have a test `test_preview_page_contains_preview`, I'll look into why that didn't catch this bug.

**Comment by smcmurtry** [comment]
That test mocks the redis function that was returning `None`: https://github.com/cds-snc/notification-admin/blob/main/tests/app/main/views/test_templates.py#L1668

I think I can update the test to make sure it still works if that function returns `{}`.

**Review by jimleroyer — APPROVED** [review]
:shipit:

**Pull request merged**
