### PR TITLE
Fix unclosed italics tag on security page

### LINKED ISSUE #496: Italics unclosed tag on french security page
image

### PR DESCRIPTION
**Pull request by anikbrazeau**
Fixes #496

### CODE REVIEW

**Comment by sastels** [comment]
oh no, this is using the old way of doing translations rather than the new way (ie `fr.csv`). Since this is a small change, the best solution is probably to close this PR and do a fresh one changing the csv file :/

**Comment by anikbrazeau** [comment]
@sastels since this is such a small change, would it be possible to throw this into an upcoming PR?

**Comment by brdunfield** [comment]
I'll add this in to the other security page updates! If that works we can close this one?

**Comment by brdunfield** [comment]
Closed by #563

**Pull request closed without merging**
