### PR TITLE
security review is under construction

### PR DESCRIPTION
**Pull request by damcom333**
I wanted to dial back the security page a bit while we are in early alpha. @YedidaZalik @willeybryan You ok with the wording and the dial back?

### CODE REVIEW

**Comment by YedidaZalik** [comment]
So sorry, I have looked on the security page and it looks the same to me. Which part am I supposed to review?

**Comment by willeybryan** [comment]
@YedidaZalik The text is in the code on the files tab of this issue.

I have extracted the text so you can more easily read it, the links won't work though but they all go to the right place in the code. 



##Data

 The security review of this service is currently ongoing.

If you have any specific security requirements please [share them with us](https://github.com/cds-snc/notification-admin/pull/139). 

This service was originally developed by [the UK government]( https://github.com/cds-snc/notification-admin/pull/139).

For your reference we are providing a [link](https://github.com/cds-snc/notification-admin/pull/139) to their security page (English only)


##Protect sensitive information

Some messages include sensitive information like security codes or password reset links.

If you’re sending a message with sensitive information, you can hide those details on the dashboard once the message has been sent. Only the message recipient will be able to see their information.

 ##User permissions and signing in
You can set different user permissions in Notification. This lets you control which team members have access to certain parts of Notification.


 ##Two-factor authentication
To sign in to Notification you’ll need to enter:'
- your email address and password
- A text message code that Notification sends to your phone

Please [contact us](https://github.com/cds-snc/notification-admin/pull/139) if your team needs email links instead of text message codes

**Comment by willeybryan** [comment]
LGTM. I made some small changes but I am going to wait to see what Yedida says.

**Comment by YedidaZalik** [comment]
Suggested replacement:

**Security**
 
GOV.UK developed the original notification (hyperlink to UK github repo) and its security system (hyperlink to GOV.UK security page). The Notification team is reviewing security for our Canadian system.  
 
Please tell us about your security needs (hyperlink to feedback page under "tell us about your security needs").

**Pull request merged**
