### PR TITLE
Design tweaks for template categories

### PR DESCRIPTION
**Pull request by amazingphilippe**
# Summary | Résumé

This PR tweaks little design details:

- Template list grid layout works better across breakpoints by introducing one media query
- Wrapped the filters nav in a div - required to play nicely with our details-polyfill. I also fixed the alignment issue we had
- Applied small font size on the category label when editing a template. 

Screenshots:

Grid:
Capture d’écran, le 2024-07-30 à 15 48 33
Capture d’écran, le 2024-07-30 à 15 48 39
Capture d’écran, le 2024-07-30 à 15 48 45

Filters:
Capture d’écran, le 2024-07-30 à 15 48 55

Category label:
Capture d’écran, le 2024-07-30 à 15 54 31

# Test instructions | Instructions pour tester la modification

Compare with the screenshots above, play around with the window size.

### CODE REVIEW

**Comment by YedidaZalik** [comment]
We are waiting for the translation for this figma content:https://www.figma.com/design/RLcM0JwlQsd2uVK3GJr5qY/Templates-%7C-Gabarits?node-id=3330-1476&t=JdTZBNSQkjrRUDWP-0
Marie-Sophie has been tagged.

**Review by andrewleith — COMMENTED** [review]
Looking side-by-side at this and staging. I don't see any differences on the template list in the large size.  Should there be some?

I do see:
  ✅  the filters being move over to the left
  ✅  the fixes and the medium and small sizes
  ✅  the smaller label on edit

**Comment by amazingphilippe** [comment]
> Should there be some?

Nope! The media query addressed the smallest viewport.

**Comment by amazingphilippe** [comment]
> We are waiting for the translation for this figma content:https://www.figma.com/design/RLcM0JwlQsd2uVK3GJr5qY/Templates-%7C-Gabarits?node-id=3330-1476&t=JdTZBNSQkjrRUDWP-0 Marie-Sophie has been tagged.

This would be for https://github.com/cds-snc/notification-admin/pull/1908 We don't need content for this one!

**Review by andrewleith — APPROVED** [review]
LGTM!

**Pull request merged**
