### PR TITLE
Bump dependencies on 2020-10-05

### PR DESCRIPTION
**Pull request by AntoineAugusti**
Trello card: https://trello.com/c/sjXUFIY9/62-recurring-dev-tasks

I'm flagging upgrades that require code changes on Trello so that we know we need to do them later on as they require more time. Flask Login + WTForms are concerned.

### CODE REVIEW

**Comment by brdunfield** [comment]
Are you planning to do npm updates in a separate PR?

**Comment by AntoineAugusti** [comment]
Oups, I'll do that as well

**Comment by brdunfield** [comment]
I think my PR caused the package.json merge conflicts, as I did not update any of the dependencies. You should be fine to just add the new ones I added, but continue to use the updated versions from this PR for existing dependencies.

**Comment by AntoineAugusti** [comment]
Yep, that was expected, no worries. Rebased based on master and kept the previous npm upgrades 👌

**Review by brdunfield — APPROVED** [review]
PR build seems to function, I tested clicking around a few pages and sending myself an email and everything seems fine.

If there's any other areas you feel need special attention / testing, let me know, but otherwise I think this looks good to go 🦑 🚢

**Pull request merged**
