### PR TITLE
feat: remove SMTP pages

### PR DESCRIPTION
**Pull request by AntoineAugusti**
Remove SMTP pages from the admin. Will do the same on the API just after.

There were no tests covering this feature so only files from `app/` are deleted.

Trello: https://trello.com/c/uzSdcwAL/297-cut-smtp-pages

### CODE REVIEW

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/779bf1d365de6f62db7f692d015b6f7a21517f45

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/33205f3030d678e909f427d03f2160585a98f8ed

**Review by jimleroyer — APPROVED** [review]
👻

**Comment by AntoineAugusti** [comment]
Thanks, the API PR is here https://github.com/cds-snc/notification-api/pull/1279

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/26c96be497026bd7d1289d908584dae86e91a628

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/99091bd64c6a07a6e2497ccb8daa6caa41ee960b

**Pull request merged**
