### PR TITLE
Fix variable display again

### PR DESCRIPTION
**Pull request by brdunfield**
I guess some of these rules were getting purged again.

### CODE REVIEW

**Comment by AntoineAugusti** [comment]
Do you know why there is not a review app here? 🤔

**Review by AntoineAugusti — APPROVED** [review]
🦑 
Screen Shot 2020-12-01 at 11 39 44

**Comment by AntoineAugusti** [comment]
It had been created but the webhook must have been lost 🤷 

https://notification-css-bug-va-s0grcp.herokuapp.com/

**Comment by brdunfield** [comment]
Hopefully just a bug on this PR and not lost for the whole repo 🤔

**Pull request merged**
