### PR TITLE
Homepage copy updates

### PR DESCRIPTION
**Pull request by anikbrazeau**
# Summary

Update to homepage copy ahead of Beta based on marketing research and strategizing.

This includes tweaks to copy like: 

- highlighting the value proposition front and centre
- emphasizing transactional use cases and features
- put less focus on mailing lists and bulk sends
- be more explicit about the API
- focus more on actions and benefits than on roles
- change language around procurement process

Figma reference: https://www.figma.com/file/dxn3FzTMOoBzqFWiJxZMhc/Homepage-Page-d-accueil?node-id=1865%3A345

Eventually would be great to update the images here to highlight relevant transactional examples and to reorder the page as shown in Figma.

### CODE REVIEW

**Review by willeybryan — APPROVED** [review]
Looks Good to me on Heroku

**Comment by AntoineAugusti** [comment]
@anikbrazeau Wondering if you want to ship this "as is" with only the content changes or if you need a developer to work on updating images/sections etc.

> Eventually would be great to update the images here to highlight relevant transactional examples and to reorder the page as shown in Figma.

**Review by RenDavidDimen — APPROVED** [review]
Looks good 👍

**Comment by AntoineAugusti** [comment]
@RenDavidDimen @anikbrazeau Just a heads up that this PR should not be merged as is. There are still changes to do based on the Figma files: shuffling sections, changing a few things.

@RenDavidDimen you're assigned to this Trello card https://trello.com/c/gEGgx51w/204-update-homepage-content

**Comment by anikbrazeau** [comment]
Outstanding changes from [Figma](https://www.figma.com/file/dxn3FzTMOoBzqFWiJxZMhc/Homepage-%7C-Page-d'accueil?node-id=1865%3A338) would include:

- upload new "Built for the Government of Canada" image and alt text
- flip the first two images/descriptions under "What you can do with GC Notify" and replace the spreadsheet with calendar
- bring the "Work more efficiently" section under "Connect your program or service"
- flip the alignment for the image and the text of "Connect your program or service", for "Work more efficiently" and for "Skip the procurement process"

**Comment by anikbrazeau** [comment]
Closed in favour of #894

**Pull request closed without merging**
