### PR TITLE
IE Detect for CSV upload

### PR DESCRIPTION
**Pull request by timarney**
@willeybryan 
@anikbrazeau 

RE: https://github.com/cds-snc/notification-api/issues/720

## Preview:
https://notification-ie-test-ppmd5fnme.herokuapp.com

## When the user visits:
Screen Shot 2020-04-09 at 11 04 50 AM

<hr>
<hr>

## Added this prompt:
Screen Shot 2020-04-09 at 11 02 04 AM
<hr>
Screen Shot 2020-04-09 at 11 02 30 AM

### CODE REVIEW

**Comment by timarney** [comment]
**Updated:**

Screen Shot 2020-04-09 at 1 58 17 PM

<hr>
If they do reach the upload page

Screen Shot 2020-04-09 at 1 58 39 PM

**Comment by willeybryan** [comment]
10/10 I love it, haven't had a chance/stomach to fire up the old IE yet.

**Comment by timarney** [comment]
Updated - https://notification-ie-test-ppmd5fnme.herokuapp.com

**Comment by timarney** [comment]
Tested with browser stack IE 11:

Screen Shot 2020-04-09 at 2 13 13 PM

**Pull request merged**
