### PR TITLE
Update terms of service content (#110)

### PR DESCRIPTION
**Pull request by brdunfield**
Closes https://github.com/cds-snc/notification-api/issues/101

### CODE REVIEW

**Comment by brdunfield** [comment]
Links still work, but the agreement page seems to be missing (was broken with the long form url as well).

**Comment by timarney** [comment]
@YedidaZalik I don't see a link to the agreement here anymore https://www.notifications.service.gov.uk/features/terms

There's still an agreement page but it uses a service_id.

```
@main.route('/services/<uuid:service_id>/agreement')
```

**Comment by YedidaZalik** [comment]
I guess they have removed it since I worked on this. @willeybryan should I rewrite this section for our purposes or just delete for now?
"Your organization must also accept our data sharing and financial agreement. Download the agreement or contact us to ask if we already have an agreement with your organization."

**Comment by willeybryan** [comment]
Delete it, we don't have anything with respect to that yet.

**Comment by brdunfield** [comment]
That link still works. It's more general vs dealing with the specific agreement that no longer exists. Ok to leave in or should I still delete?

**Comment by YedidaZalik** [comment]
Which link do you mean?  
Or if this question is not for me, no worries!

**Comment by brdunfield** [comment]
The contact us link in the Leaving Notification section:

"You can leave Notification at any time. Just _contact us_ and we’ll close your account."

**Pull request merged**
