### PR TITLE
Fr dashboard update

### PR DESCRIPTION
**Pull request by timarney**
**Fixes:**
https://github.com/cds-snc/notification-api/issues/751

**Staging preview link:**
https://notification-fr-dashboa-btrmiz.herokuapp.com

Screen Shot 2020-04-28 at 1 29 02 PM

<hr>

Screen Shot 2020-04-28 at 1 29 14 PM

### CODE REVIEW

**Comment by ClementineHahn** [comment]
Looks good to me for the courriel part.
Only caveat would be if "0" is displayed technically there should be no "s" at the end of "message" and "envoyé". It should be : 
-  " 0 message texte envoyé" _if number is zero or one_
- " 2 messages texte envoyés" _if number is two or plus_

**Comment by timarney** [comment]
Perfect - I'll test with 0's and add screens here.

**Comment by timarney** [comment]
Updated.  

**Note:** There's also the case where 1 text message exists vs 0 text messages

Screen Shot 2020-04-30 at 7 40 17 AM

Screen Shot 2020-04-30 at 7 40 37 AM

<hr>
Screen Shot 2020-04-30 at 7 41 17 AM
Screen Shot 2020-04-30 at 7 41 32 AM

<hr>
Screen Shot 2020-04-30 at 7 44 07 AM

**Comment by willeybryan** [comment]
0 messages texte envoyé 
should be
0 messages texte**s** envoyé 

Like
0 messages courriel**s**

**Comment by willeybryan** [comment]
Oh dear, now we are in discussion about the pluralty of zero in french, please stand by.

**Comment by willeybryan** [comment]
http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?id=3642

**Pull request merged**
