### PR TITLE
Request to go live process in service settings

### PR DESCRIPTION
**Pull request by AntoineAugusti**
# Summary | Résumé

Adds the "Request to go live" process to "Service settings". Service owners will be presented with a checklist of action items to do before being able to request to go live. Once the checklist has been completed, this will submit a go-live request to Freshdesk that will be handled by the Notify team.

You'll see that this PR deletes more code than it adds - it's because I reused and cleaned up the GDS go-live process.

# Test instructions | Instructions pour tester la modification

You can test this out locally our using the review app. Create a trial service, go to service settings and follow the "Request to live" process. You should be able to leave it/resume it, even when signing off/signing in. The process is at the service level, not at the user account level.

# Help requested | Aide requise

Most of the "request to go live" data is temporary, such as accepting terms of use or filling in the use case form. This is stored in Redis and will disappear after 30 or 90 days. I'd like your opinion about the implementation.

The most important thing to look at in this PR are tests, make sure that nothing critical is left off.

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

We don't store the "use case data" in the Notify database yet. This will likely be addressed later. We will store that on the Notify side or in the new CRM, we'll see. Anyway, this will require new database columns or a whole new table and a dedicated API endpoint.

Trello card: https://trello.com/c/ZMoWPX2T/294-implement-new-go-live-in-gc-notify

### CODE REVIEW

**Comment by willeybryan** [comment]
So simple yet elegant. Since this is better than what we have now I am good deploying this as is. 
If there was more time I would change:
Should the button say request to live? or the text say press the button below to request to go live?
Can it be on one line?
image

**Review by willeybryan — COMMENTED** [review]
LGTM, but what to I know

**Comment by AntoineAugusti** [comment]
@willeybryan The [Figma file](https://www.figma.com/file/A4yAAkCGUaqoaTjpWL411i/Going-live-%7C-Activation-du-service?node-id=266%3A178) used this wording for this piece so I'll let @anikbrazeau give it a look and provide some feedback.

**Comment by anikbrazeau** [comment]
Yeah, you're right `Request to go live` would be ideal to match expectation.
In French, let's stick with `Activer votre service` to keep it short.

**Review by anikbrazeau — CHANGES_REQUESTED** [review]
This is looking good! 
Can we make a couple of small tweaks?

The button to enter the go live flow to match heading and expectations: 
`Request to go live`
`Activer votre service`

The text below the checklist so it's not confusing as they're not ready yet:
Remove `Ready to go live?`/`Prêt à activer votre service?` before all steps are complete

The green feedback once the request is submitted so it's less redundant: 
`Your request was submitted.`
`Votre demande a été soumise`

**Comment by AntoineAugusti** [comment]
@anikbrazeau Just did your requested content changes in the latest commit

**Review by anikbrazeau — APPROVED** [review]
Thanks! :D

**Review by dorianjp — COMMENTED** [review]
Some great mocks in the tests for full cycle of submission and a good reduction in unused code, nice.

I see now REDIS_ENABLED is required for this functionality to work and some parts of the admin will fail silently if it is not enabled. As this mostly affects developers, can you add a warning or messaging @ boot when REDIS_ENABLED==False. Perhaps mentioning some features will not work, or even a general message is fine.

**Review by dorianjp — APPROVED** [review]
lgtm, nice work

**Pull request merged**
