### PR TITLE
Update the create password page

### PR DESCRIPTION
**Pull request by jzbahrai**
# Summary | Résumé

Update the create password page according to https://www.figma.com/file/T6gN6GxBubbXvAHGtgUxHl/Security-features?node-id=4%3A86

also edited the call for the forced password reset flow
Blocked by: https://github.com/cds-snc/notification-api/pull/1526

### CODE REVIEW

**Review by andrewleith — APPROVED** [review]
LGTM. 

- I see the new email template when trying to login as a user with `password_expired` = `true`
- I still see the old reset password template when trying to reset my password through the sign in page

**Comment by amazingphilippe** [comment]
@jzbahrai  Is this done, but not deployed because of Heroku?

**Comment by jzbahrai** [comment]
@amazingphilippe sorry i didnt see your comment before merging. This had put the password requirements and a route to the new forced password reset page. you should be able to test it on staging.

**Comment by amazingphilippe** [comment]
I can't see the password requirements on staging. This is what I get:
Capture d’écran, le 2022-04-20 à 15 22 42

**Comment by amazingphilippe** [comment]
Just noting that autocomplete here also isn't necessarily providing wanted assistance.

**Comment by jzbahrai** [comment]
@amazingphilippe can you test again? I see the correct screens (it might not have been deployed when you tested
Screen Shot 2022-04-20 at 3 47 10 PM
)

**Pull request merged**
