### PR TITLE
Update wording in ToS

### PR DESCRIPTION
**Pull request by AntoineAugusti**

### CODE REVIEW

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/44d1311ba029a7e3aa07db148b052530b99e7397

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/056704832b4516d4c1217e98433ad99661529a10

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/da661038b6ec1b029ab52aa65874d2f6c5690cdc

**Review by jimleroyer — APPROVED** [review]
LGTM

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/527f96eaa7b770450aeca4b82de9f71b7fe96d41

**Pull request merged**
