### PR TITLE
feat: add new email error messages

### PR DESCRIPTION
**Pull request by AntoineAugusti**
Translate new error messages from https://github.com/cds-snc/notification-api/pull/1275

Trello: https://trello.com/c/HEZcloCO/460-better-error-messages-for-emails-in-case-of-failures

Screen Shot 2021-04-22 at 10 04 56

### CODE REVIEW

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/f2dbbfa7589d5ef8807384db57f308acb922f31a

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/c8845886b5f5a56aff315df9be6258a09c4a89df

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/590f3e17c5624a47599d3b432f82e6705cc61b02

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/2a0d798df9eb51283ce4b02260e2eb4dd802f37d

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/74548581fe20b3eb83baddfc02d173ecee980e5d

**Review by QuanNguyen-CDS — APPROVED** [review]

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/eb658e1766b57c938385667c4f3385a1a9f4a35c

**Pull request merged**
