### PR TITLE
Bugfix - Table styling on the csv "review before sending" page

### PR DESCRIPTION
**Pull request by smcmurtry**
# Summary | Résumé

Connected to https://github.com/cds-snc/notification-planning/issues/744

On the CSV review page w/ no errors, there were actually 2 tables which I have combined. On the error page there was only 1 table and all I had to do there was remove some problematic javascript that was getting called.

Screen Shot 2022-09-23 at 3 50 56 PM
Screen Shot 2022-09-23 at 3 49 55 PM

## Test instructions

Try doing a CSV send using a CSV with errors (bad phone number) and without. Make sure that the issue described in https://github.com/cds-snc/notification-planning/issues/744 has been fixed.

### CODE REVIEW

**Comment by amazingphilippe** [comment]
Ok, so I was able to test this in the other scenario. And the index column works well! However, it does break the overflow scrolling provided by "fullscreen-table" I think. Here are some videos comparing this PR and staging:

Staging: https://youtu.be/Py0RSSY47NY

PR: https://youtu.be/KkG4L6Kc_NM

**Comment by andrewleith** [comment]
> Ok, so I was able to test this in the other scenario. And the index column works well! However, it does break the overflow scrolling provided by "fullscreen-table" I think. Here are some videos comparing this PR and staging:
> 
> Staging: https://youtu.be/Py0RSSY47NY
> 
> PR: https://youtu.be/KkG4L6Kc_NM

Not sure the exact specifics, but this may help you @smcmurtry: looks overflow is set to hidden. `overflow-x: scroll` maye help!

**Comment by smcmurtry** [comment]
> Not sure the exact specifics, but this may help you @smcmurtry: looks overflow is set to hidden by `.fullscreen-content`. `overflow-x: scroll` may help!

Thank you @andrewleith! I believe that has solved the issue.

**Review by amazingphilippe — APPROVED** [review]
Looks good to me with the overflow x!

**Pull request merged**
