### PR TITLE
fix: update occurrences of 'GC Notification' to 'Notification GC'

### PR DESCRIPTION
**Pull request by andrewleith**
# Summary | Résumé

This PR updates all occurrences of `GC Notification` in French to `Notification GC`.

### CODE REVIEW

**Review by sastels — APPROVED** [review]

**Comment by sastels** [comment]
Just noticed!
image

**Comment by sastels** [comment]
and
image

**Comment by sastels** [comment]
Also
image
But maybe these are all coming from GCA?

**Review by jzbahrai — APPROVED** [review]

**Comment by sastels** [comment]
ah yeah when I'm logged in the bottom is good 🙃 
image

**Review by sastels — APPROVED** [review]
:shipit: if what I notices was coming from GCA.

**Comment by andrewleith** [comment]
> and image

Good catch on this one - it is in ADMIN but instead of the text being `GC Notification` its `GC&nbsp;Notification` so I'll look for occurences of that too! 🙇

**Pull request merged**
