### PR TITLE
Link fixes for nav on descender and bar underline 

### PR DESCRIPTION
**Pull request by dorianjp**
Fixes:
https://trello.com/c/SzPvvHSa/353-nav-bug-menu-item-highlight-underline-longer-than-element
https://trello.com/c/i67naX7Q/330-nav-bug-descender-cuts-underline-on-links

* Link underlines on hover no longer cut on char descender0
* Underlines on nav bar are length of text only

### CODE REVIEW

**Review by anikbrazeau — COMMENTED** [review]
Descender spacing and nav bar underline look good. 

Not sure if this is related to the changes in this fix, but when clicking through in French things go to two lines?
Screen Shot 2021-03-08 at 7 37 22 AM

**Comment by dorianjp** [comment]
> Descender spacing and nav bar underline look good.
> 
> Not sure if this is related to the changes in this fix, but when clicking through in French things go to two lines?
> Screen Shot 2021-03-08 at 7 37 22 AM

Good catch,

The inheritance in divs changed this to stop forcing it to one line and wrap when shorter. I can have it go either way at this point @anikbrazeau , let me know which is preferred.

**Comment by anikbrazeau** [comment]
I think keeping it to one line for the menu items would be preferred with the 'More' option when it exceeds the entire length.

Screen Shot 2021-03-08 at 4 46 19 PM

**Comment by dorianjp** [comment]
> I think keeping it to one line for the menu items would be preferred with the 'More' option when it exceeds the entire length.
> 
> Screen Shot 2021-03-08 at 4 46 19 PM

I can make the one line work as expected. The more issue I think is figured out for now where Eric advised to shift the breakpoint for the Menu button up one size so we only see this menu in the desktop viewport.

**Comment by anikbrazeau** [comment]
Looks good. 
Should these be underlined/links also? 

`Sign in` / `Your account`
`English` / `Français`

Screen Shot 2021-03-09 at 8 04 24 AM

**Comment by dorianjp** [comment]
@anikbrazeau updated the left alignment to be closer to production, the other links should be in their own trello card to help avoid merge conflicts with other developers scoping work on different pieces. 

Once you approve, I'll merge this into staging.

**Review by anikbrazeau — APPROVED** [review]
Looks great, thanks Dorian! 🚀

**Pull request merged**
