### PR TITLE
feat: test html fragments for a11y issues

### PR DESCRIPTION
**Pull request by maxneuvians**
This PR adds the ability to scan HTML fragments for a11t issues using the a11y tracker API. This PR will remain in draft until the a11y tools can report back results of the scan to the PR.

### CODE REVIEW

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/notification-admin/0a567d2df57b6a5764255960ee01a7625bf67a87

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/notification-admin/0a567d2df57b6a5764255960ee01a7625bf67a87

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification-admin/0a567d2df57b6a5764255960ee01a7625bf67a87

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/0a567d2df57b6a5764255960ee01a7625bf67a87

**Comment by AntoineAugusti** [comment]
@maxneuvians When do you think we can merge this one?

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/df183d78caac84881e8bcf5b190793cdfb2c9e7c

**Comment by maxneuvians** [comment]
I would wait till Monday to merge this - the last comment from me was automatically added through the callback lambda. Otherwise this should be GTG

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/b0eea32984e99aa2d341e17976f3b340af9bf859

**Review by AntoineAugusti — APPROVED** [review]

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/cc07a30cf971ab0ea2c0eba8817b250095aae612

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/7ed077e3b1be94529237a2198ed60d164992535c

**Pull request merged**
