### PR TITLE
feat: update social media image

### PR DESCRIPTION
**Pull request by AntoineAugusti**

### CODE REVIEW

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/9f8c66c021cf97d0af2c981b5b1ec16eb1cf4c68

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/2fd14cb85430346da95ad8e9e63c091291ef4c51

**Review by willeybryan — APPROVED** [review]
lgtm

**Comment by maxneuvians** [comment]
https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fnotification/334fe13b6391a787c2c5f5a1867ec1fcd7d7c8d8

**Pull request merged**
