### PR TITLE
Live Banner / Pending live status

### PR DESCRIPTION
**Pull request by jimleroyer**
# Summary | Résumé

[Added label to indicate 'in progress' request to go live.](https://trello.com/c/YrDckOOs/387-trial-contentdevelopment-banner)

# Test instructions | Instructions pour tester la modification

1. Login into the application and select your favorite service still in Trial.
2. Test the Live Banner, its content and links.
3. Proceed to the request to go live process.
4. Get back to your favorite service in Trial.
5. Test the Live Banner, its content and links with updated progress status.

# Reviewer checklist | Liste de vérification du réviseur

This is a suggested checklist of questions reviewers might ask during their review | Voici une suggestion de liste de vérification comprenant des questions que les réviseurs pourraient poser pendant leur examen :

- [ ] Does this meet a user need? | Est-ce que ça répond à un besoin utilisateur?
- [ ] Is it accessible? | Est-ce que c’est accessible?
- [ ] Is it translated between both offical languages? | Est-ce dans les deux langues officielles?
- [ ] Is the code maintainable? | Est-ce que le code peut être maintenu?
- [ ] Have you tested it? | L’avez-vous testé?
- [ ] Are there automated tests? | Y a-t-il des tests automatisés?
- [ ] Does this cause automated test coverage to drop? | Est-ce que ça entraîne une baisse de la quantité de code couvert par les tests automatisés?
- [ ] Does this break existing functionality? | Est-ce que ça brise une fonctionnalité existante?
- [ ] Should this be split into smaller PRs to decrease change risk? | Est-ce que ça devrait être divisé en de plus petites demandes de tirage (« pull requests ») afin de réduire le risque lié aux modifications?
- [ ] Does this change the privacy policy? | Est-ce que ça entraîne une modification de la politique de confidentialité?
- [ ] Does this introduce any security concerns? | Est-ce que ça introduit des préoccupations liées à la sécurité?
- [ ] Does this significantly alter performance? | Est-ce que ça modifie de façon importante la performance?
- [ ] What is the risk level of using added dependencies? | Quel est le degré de risque d’utiliser des dépendances ajoutées?
- [ ] Should any documentation be updated as a result of this? (i.e. README setup, etc.) | Faudra-t-il mettre à jour la documentation à la suite de ce changement (fichier README, etc.)?

### CODE REVIEW

**Review by AntoineAugusti — APPROVED** [review]
LGTM on the code side!

Commit history is a bit weird, maybe rebase with master?

**Review by e-pang — APPROVED** [review]
Thanks Jimmy, this is looking great! Just a couple of notes - no action needed on them after our discussion on slack (but wanted to document for myself). 

1. Link shouldn’t lose underline on hover - leave as is for now, I need to think about what the hover state should be for text links across notify. @JuliannaR curious if the cursor changing in enough of an indication?

2. Focus state is messy - should be an outline of banner and link elements - from our discussion on slack it sounds like this is defined by the browser. There may be some things we can do but will require more effort. IMO we need to audit and revisit focus styles across notify. 

3. When the service name goes to a second, third, etc. line the banner should stay next to it - currently it falls to a new line even when there's space. Not a big concern, it's a nice to have if possible. 

I also recommend adding @JuliannaR as a reviewer :).

**Comment by jimleroyer** [comment]
@e-pang 

Re 1: I removed the behavior of the underline disappearing on hover once you asked me to do it. It might be better to make the underline disappear and revert to previous behavior IMHO. After reading some a11y documentation, I realize this is a good visual signal for color impaired people who need a cue if it is really a link, i.e. we'd probably want also color change on hover/focus state, but the underline removal provides that cue as well for color impaired people. Also note that I initially followed what other links do in the application, i.e. underline is disappears on hover.

Re 2: It might be customizable but get out of my comfort zone. I will need to revisit and see how we can customize these. Doing this work in one sweep might be good as we could learn on the how but also estimate the effort/priority as well, this takes more time to tailor and ramp up.

Re 3: This is fixed.

**Comment by jimleroyer** [comment]
[[Trial Content][Development] Banner](https://trello.com/c/YrDckOOs/387-trial-contentdevelopment-banner)

**Pull request merged**
