### PR TITLE
A11y/fix scheduler month buttons

### PR DESCRIPTION
**Pull request by andrewleith**
# Summary | Résumé

This PR updates the scheduler component so in addition to visually disabling the month toggle buttons, they are also disabled in the markup (i.e. using the `disabled` attribute) so that screen readers know they are disabled.

## Related cards
- https://github.com/cds-snc/notification-planning/issues/1474

# Test instructions | Instructions pour tester la modification
- Login to notify, navigate to your service
- Send a bulk email
   - Choose a template
   - Click **Yes, add recipients**
   - Select **Many recipients** and click **Continue**
   - Select **Choose a file** and upload a CSV (you only need one recipient)
   - Scroll down and click **Schedule for later**
   - Ensure the month toggles (the chevron icons to the left and right of the month name) cannot be tabbed to

### CODE REVIEW

**Comment by amazingphilippe** [comment]
I'm testing this locally. The file upload won't work for bulk messages on PR review apps.

- I made sure to `npm run build` We should add this for the reviewer checklist.
- It seems like all focus is removed and I can't select any dates:
image

**Review by amazingphilippe — APPROVED** [review]
lgtm! 🚀

**Comment by andrewleith** [comment]
> `npm run tailwind` is the one I needed.

Hmm I wonder why that was necessary.  I had run it and committed the result (`scheduler.min.js`) so it should have worked without you needing to do that. Perhaps a caching issue on your local server?

**Review by whabanks — APPROVED** [review]
LGTM! Tested locally and the arrows are not tab-able to!

**Pull request merged**
